### ISSUE TITLE
Timezones with two slashes returns undefined

### ISSUE THREAD

**Issue by mchangrh** [spencermountain/timezone-soft#9]
Timezones such as
`America/Indiana/Knox`, `america/argentina/buenos_aires` and `America/North_Dakota/New_Salem`
aren't parsed properly and return undefined. 

is this intentional?
they seem to have be removed in https://github.com/spencermountain/timezone-soft/commit/6fda1975bdee386070e390fd3d4f9c2ca5ce124d and skipped in https://github.com/spencermountain/timezone-soft/blob/5c68a03921551f2ee64ce848f70c8666bf6fe5da/test/allwords.test.js#L6-L11

**Comment by spencermountain** [comment]
hey Michael, thanks for the good issue - yeah, those should work.
hah, nice find on the skipped test. I can do a fix this week, or PRs welcome if you'd like something quicker.
cheers

**Comment by mchangrh** [comment]
I'll get to work on a PR!

**Comment by mchangrh** [comment]
EDIT: it seems like the list of oldZones itself is old, I'll go through and clean it up

> I tried populating `data/01-iana.js` with the latest and complete tzdb list but it seems that a lot of keys are lost during packing/unpacking (~144), even after re-creating the pack with `npm run pack`.
> I've included updates on my fork https://github.com/mchangrh/timezone-soft/commit/318abd749f1a8619494c3e2f1ea544f24a389e6c but I'm not sure where the lost keys might be.
